#!/usr/bin/env bash
# Description: Test `stanza rules` (print, install, check, uninstall, --local,
#              --json). HOME points at a temp directory for every case so the
#              real ~/.claude is never read or written.
set -e

STANZA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." && pwd)"
STANZA="$STANZA_DIR/bin/stanza"
SELF_VERSION=$(head -1 "$STANZA_DIR/VERSION" | tr -d '[:space:]')
ORIG_HOME="$HOME"
PASS=0
FAIL=0

export GIT_AUTHOR_NAME=t GIT_AUTHOR_EMAIL=t@t GIT_COMMITTER_NAME=t GIT_COMMITTER_EMAIL=t@t
export NO_COLOR=1

# --- Helpers ---------------------------------------------------------------

assert_eq() {
    local label="$1" expected="$2" actual="$3"
    if [[ "$actual" == "$expected" ]]; then
        echo "  PASS: $label"
        PASS=$((PASS + 1))
    else
        echo "  FAIL: $label (expected '$expected', got '$actual')"
        FAIL=$((FAIL + 1))
    fi
}

assert_contains() {
    local label="$1" haystack="$2" needle="$3"
    if [[ "$haystack" == *"$needle"* ]]; then
        echo "  PASS: $label"
        PASS=$((PASS + 1))
    else
        echo "  FAIL: $label (expected to contain '$needle', got '$haystack')"
        FAIL=$((FAIL + 1))
    fi
}

assert_not_contains() {
    local label="$1" haystack="$2" needle="$3"
    if [[ "$haystack" != *"$needle"* ]]; then
        echo "  PASS: $label"
        PASS=$((PASS + 1))
    else
        echo "  FAIL: $label (expected NOT to contain '$needle', got '$haystack')"
        FAIL=$((FAIL + 1))
    fi
}

# Fresh temp HOME plus a git repo to run in. Leaves the shell in the repo.
setup() {
    TEST_TMPDIR=$(mktemp -d)
    export HOME="$TEST_TMPDIR/home"
    mkdir -p "$HOME"
    git -c init.defaultBranch=main init -q "$TEST_TMPDIR/repo"
    cd "$TEST_TMPDIR/repo"
    GLOBAL_RULE="$HOME/.claude/rules/stanza.md"
    LOCAL_RULE="$TEST_TMPDIR/repo/.claude/rules/stanza.md"
}

cleanup() {
    cd /
    export HOME="$ORIG_HOME"
    if [[ -n "${TEST_TMPDIR:-}" && -d "$TEST_TMPDIR" && "$TEST_TMPDIR" == *tmp* ]]; then
        rm -rf "$TEST_TMPDIR"
    fi
    unset TEST_TMPDIR
}

trap cleanup EXIT INT TERM

# --- Tests -----------------------------------------------------------------

test_print() {
    echo ""
    echo "stanza rules prints the rule text without a stamp"
    setup

    local out
    out=$("$STANZA" rules)
    assert_eq "first line is the title" "# Stanza releases" "$(head -1 <<< "$out")"
    assert_not_contains "no generated stamp" "$out" "generated by stanza"
    assert_contains "documents the release merge subject" "$out" 'version [release]: v<version> - PR #<N>'
    assert_eq "nothing written" "" "$(ls -A "$HOME")"

    cleanup
}

test_install_idempotent() {
    echo ""
    echo "install writes a stamped file; a second install is a no-op"
    setup

    local out
    out=$("$STANZA" rules install)
    assert_contains "reports the write" "$out" "wrote   $GLOBAL_RULE"
    assert_eq "stamp line" \
        "<!-- generated by stanza $SELF_VERSION (mode=global); do not edit; regenerate with: stanza rules install -->" \
        "$(head -1 "$GLOBAL_RULE")"
    assert_eq "body follows a blank line" "# Stanza releases" "$(sed -n 3p "$GLOBAL_RULE")"

    local before
    before=$(cksum < "$GLOBAL_RULE")
    out=$("$STANZA" rules install)
    assert_contains "second install reports current" "$out" "current $GLOBAL_RULE"
    assert_eq "file unchanged" "$before" "$(cksum < "$GLOBAL_RULE")"

    assert_eq "quiet install prints the path" "$GLOBAL_RULE" "$("$STANZA" -q rules install)"

    cleanup
}

test_check_states() {
    echo ""
    echo "check reports ok, drifted, and missing"
    setup

    local out code
    "$STANZA" rules install >/dev/null
    code=0; out=$("$STANZA" rules check 2>&1) || code=$?
    assert_eq "ok exits 0" "0" "$code"
    assert_contains "global row ok" "$out" "global  ok       $GLOBAL_RULE"
    assert_contains "local row missing (no repo copy)" "$out" "local   missing  $LOCAL_RULE"

    echo "hand edit" >> "$GLOBAL_RULE"
    code=0; out=$("$STANZA" rules check 2>&1) || code=$?
    assert_eq "drifted exits 1" "1" "$code"
    assert_contains "global row drifted" "$out" "global  drifted"

    "$STANZA" rules install --force >/dev/null
    sed "s/generated by stanza $SELF_VERSION/generated by stanza 0.0.1/" "$GLOBAL_RULE" > "$GLOBAL_RULE.tmp"
    mv "$GLOBAL_RULE.tmp" "$GLOBAL_RULE"
    code=0; out=$("$STANZA" rules check 2>&1) || code=$?
    assert_eq "stale version stamp exits 1" "1" "$code"
    assert_contains "stale version stamp is drift" "$out" "global  drifted"

    rm -f "$GLOBAL_RULE"
    code=0; out=$("$STANZA" rules check 2>&1) || code=$?
    assert_eq "missing everywhere exits 1" "1" "$code"
    assert_contains "global row missing" "$out" "global  missing"

    cleanup
}

test_install_refuses_unstamped() {
    echo ""
    echo "install refuses a file stanza did not write; --force overwrites it"
    setup

    mkdir -p "$(dirname "$GLOBAL_RULE")"
    printf '# my own notes\n' > "$GLOBAL_RULE"

    local err code=0
    err=$("$STANZA" rules install 2>&1) || code=$?
    assert_eq "refusal exits 1" "1" "$code"
    assert_contains "explains the refusal" "$err" "was not generated by stanza"
    assert_eq "file left alone" "# my own notes" "$(cat "$GLOBAL_RULE")"

    code=0
    "$STANZA" rules install --force >/dev/null || code=$?
    assert_eq "--force exits 0" "0" "$code"
    assert_contains "--force wrote the stamp" "$(head -1 "$GLOBAL_RULE")" "generated by stanza"

    cleanup
}

test_local_scope() {
    echo ""
    echo "--local writes into the repo; check reports both locations"
    setup

    "$STANZA" rules install >/dev/null
    "$STANZA" rules install --local >/dev/null
    assert_contains "local stamp names the local mode" "$(head -1 "$LOCAL_RULE")" "(mode=local)"
    assert_contains "local stamp regenerates with --local" "$(head -1 "$LOCAL_RULE")" "stanza rules install --local -->"

    local out code=0
    out=$("$STANZA" rules check 2>&1) || code=$?
    assert_eq "both ok exits 0" "0" "$code"
    assert_contains "global row ok" "$out" "global  ok"
    assert_contains "local row ok" "$out" "local   ok       $LOCAL_RULE"

    cd "$TEST_TMPDIR"
    local err
    code=0; err=$("$STANZA" rules install --local 2>&1) || code=$?
    assert_eq "--local outside a repo exits 1" "1" "$code"
    assert_contains "--local outside a repo explains why" "$err" "not in a git repository"

    cleanup
}

test_uninstall() {
    echo ""
    echo "uninstall removes a generated file and refuses an unstamped one"
    setup

    "$STANZA" rules install >/dev/null
    local out code=0
    out=$("$STANZA" rules uninstall) || code=$?
    assert_eq "removal exits 0" "0" "$code"
    assert_contains "reports the removal" "$out" "removed $GLOBAL_RULE"
    assert_eq "file gone" "no" "$([[ -f "$GLOBAL_RULE" ]] && echo yes || echo no)"

    code=0; out=$("$STANZA" rules uninstall) || code=$?
    assert_eq "absent exits 0" "0" "$code"
    assert_contains "reports absent" "$out" "absent  $GLOBAL_RULE"

    printf '# my own notes\n' > "$GLOBAL_RULE"
    local err
    code=0; err=$("$STANZA" rules uninstall 2>&1) || code=$?
    assert_eq "unstamped refusal exits 1" "1" "$code"
    assert_contains "explains the refusal" "$err" "was not generated by stanza"
    assert_eq "unstamped file kept" "# my own notes" "$(cat "$GLOBAL_RULE")"

    cleanup
}

test_json() {
    echo ""
    echo "--json output carries command, action, path, and status"
    setup

    local out
    out=$("$STANZA" --json rules install)
    assert_contains "command" "$out" '"command":"rules"'
    assert_contains "action" "$out" '"action":"install"'
    assert_contains "path" "$out" "\"path\":\"$GLOBAL_RULE\""
    assert_contains "status wrote" "$out" '"status":"wrote"'

    out=$("$STANZA" rules install --json)
    assert_contains "flag after subcommand, status up_to_date" "$out" '"status":"up_to_date"'

    out=$("$STANZA" --json rules check)
    assert_contains "check overall status" "$out" '"action":"check","status":"ok"'
    assert_contains "check lists locations" "$out" "{\"scope\":\"global\",\"path\":\"$GLOBAL_RULE\",\"status\":\"ok\"}"

    out=$("$STANZA" --json rules uninstall)
    assert_contains "uninstall status removed" "$out" '"status":"removed"'

    cleanup
}

test_flag_validation() {
    echo ""
    echo "flags that do not apply to an action are rejected"
    setup

    local err code=0
    err=$("$STANZA" rules check --force 2>&1) || code=$?
    assert_eq "check --force exits 1" "1" "$code"
    assert_contains "check --force explains" "$err" "--force applies only to 'rules install'"

    code=0; err=$("$STANZA" rules check --local 2>&1) || code=$?
    assert_eq "check --local exits 1" "1" "$code"

    code=0; err=$("$STANZA" rules bogus 2>&1) || code=$?
    assert_eq "unknown token exits 1" "1" "$code"

    code=0; "$STANZA" rules install -v >/dev/null || code=$?
    assert_eq "-v after the action is accepted" "0" "$code"
    code=0; err=$("$STANZA" rules install -vx 2>&1) || code=$?
    assert_eq "malformed -v flag exits 1" "1" "$code"

    assert_contains "help lists the actions" "$("$STANZA" rules --help)" "stanza rules install [--local] [--force]"

    cleanup
}

test_marker_in_prose() {
    echo ""
    echo "a hand-written rule that mentions the marker phrase is not ours"
    setup

    local notes
    notes=$'# my own notes\n\nRelease commits here are generated by stanza; leave them.'
    mkdir -p "$(dirname "$GLOBAL_RULE")"
    printf '%s\n' "$notes" > "$GLOBAL_RULE"

    local err code=0
    err=$("$STANZA" rules install 2>&1) || code=$?
    assert_eq "install refuses without --force" "1" "$code"
    assert_eq "install left the file alone" "$notes" "$(cat "$GLOBAL_RULE")"

    code=0; err=$("$STANZA" rules uninstall 2>&1) || code=$?
    assert_eq "uninstall refuses" "1" "$code"
    assert_eq "uninstall left the file alone" "$notes" "$(cat "$GLOBAL_RULE")"

    cleanup
}

test_write_failure() {
    echo ""
    echo "install fails loudly when the rule file cannot be written"
    setup

    if [[ $EUID -eq 0 ]]; then
        echo "  SKIP: root ignores directory permissions"
        cleanup
        return
    fi

    local dir err code=0
    dir=$(dirname "$GLOBAL_RULE")
    mkdir -p "$dir"
    chmod 0555 "$dir"
    err=$("$STANZA" rules install 2>&1) || code=$?
    chmod 0755 "$dir"
    assert_eq "unwritable target exits 1" "1" "$code"
    assert_contains "explains the failure" "$err" "could not write $GLOBAL_RULE"
    assert_eq "nothing left behind" "" "$(ls -A "$dir")"

    cleanup
}

# Run the bash completion for a command line; prints the candidates.
complete_line() {
    (
        _init_completion() {
            words=("${COMP_WORDS[@]}")
            cword=$COMP_CWORD
            cur=${words[cword]}
            prev=${words[cword - 1]}
        }
        source "$STANZA_DIR/completions/stanza.bash"
        COMP_WORDS=("$@")
        COMP_CWORD=$(($# - 1))
        _stanza_completion
        echo "${COMPREPLY[*]}"
    )
}

test_completion_flags() {
    echo ""
    echo "bash completion offers --local and --force only where they apply"

    local out
    out=$(complete_line stanza rules install --)
    assert_contains "install offers --force" "$out" "--force"
    assert_contains "install offers --local" "$out" "--local"

    out=$(complete_line stanza rules uninstall --)
    assert_contains "uninstall offers --local" "$out" "--local"
    assert_not_contains "uninstall omits --force" "$out" "--force"

    out=$(complete_line stanza rules check --)
    assert_not_contains "check omits --local" "$out" "--local"
    assert_not_contains "check omits --force" "$out" "--force"
    assert_contains "check offers --json" "$out" "--json"

    out=$(complete_line stanza rules --)
    assert_not_contains "print omits --local" "$out" "--local"
}

test_uninstall_script() {
    echo ""
    echo "uninstall.sh removes a generated rule and keeps a hand-written one"
    setup

    local prefix="$TEST_TMPDIR/prefix" notes
    notes=$'# my own notes\n\nRelease commits here are generated by stanza; leave them.'
    mkdir -p "$prefix/bin" "$(dirname "$GLOBAL_RULE")"
    : > "$prefix/bin/stanza"
    printf '%s\n' "$notes" > "$GLOBAL_RULE"
    "$STANZA_DIR/uninstall.sh" --prefix="$prefix" -y >/dev/null
    assert_eq "hand-written rule kept" "$notes" "$(cat "$GLOBAL_RULE")"

    "$STANZA" rules install --force >/dev/null
    : > "$prefix/bin/stanza"
    "$STANZA_DIR/uninstall.sh" --prefix="$prefix" -y >/dev/null
    assert_eq "generated rule removed" "no" "$([[ -f "$GLOBAL_RULE" ]] && echo yes || echo no)"

    cleanup
}

test_install_script_prefix() {
    echo ""
    echo "install.sh --prefix installs a binary that finds its library"
    setup

    local prefix="$TEST_TMPDIR/prefix" out
    mkdir -p "$HOME/.claude"
    printf 'y' | "$STANZA_DIR/install.sh" --prefix="$prefix" --no-completions >/dev/null 2>&1
    out=$(cd / && "$prefix/bin/stanza" help 2>&1 | head -1) || true
    assert_contains "installed binary finds its library" "$out" "stanza v$SELF_VERSION"
    assert_eq "installer wrote the rule" "yes" "$([[ -f "$GLOBAL_RULE" ]] && echo yes || echo no)"

    cleanup
}

# --- Run -------------------------------------------------------------------

test_print
test_install_idempotent
test_check_states
test_install_refuses_unstamped
test_local_scope
test_uninstall
test_json
test_flag_validation
test_marker_in_prose
test_write_failure
test_completion_flags
test_uninstall_script
test_install_script_prefix

echo ""
echo "Results: $PASS passed, $FAIL failed"
[[ $FAIL -eq 0 ]] || exit 1
